# Generated by Django 5.0.7 on 2024-07-11 07:35

import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=5)),
                ('stock', models.PositiveIntegerField()),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='image/product', verbose_name='Image')),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
