# Generated by Django 5.0.7 on 2024-07-12 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '__first__'),
        ('profile', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='district.district'),
        ),
    ]
