# Generated by Django 5.0.7 on 2024-07-13 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
        ('profile', '0004_alter_profile_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('born', 'Born'), ('current', 'Current')], max_length=255)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_address', to='district.district')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_address', to='profile.profile')),
            ],
            options={
                'verbose_name': 'ProfileAddress',
                'verbose_name_plural': 'ProfileAddress',
                'ordering': ['-created_on'],
            },
        ),
    ]
