# Generated by Django 4.1.1 on 2024-09-15 06:05

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('examType', models.CharField(choices=[('Mid-term', 'Mid Term'), ('Final', 'Final'), ('Quiz', 'Quiz'), ('Assignment', 'Assignment')], default='Final', max_length=255)),
                ('examDate', models.DateField()),
                ('maxScore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='image/exam', verbose_name='Image')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.subject')),
            ],
        ),
    ]
