# Generated by Django 4.1.1 on 2024-09-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_subject_code_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='examDate',
            field=models.DateTimeField(),
        ),
    ]
